const mathFacts = [
                  "The first computer 'bug' was a real moth found in a relay.",
                  "Binary (0 and 1) was invented by Gottfried Leibniz in 1679.",
                  "A 'Nibble' is exactly 4 bits, or half a Byte.",
                  "The first 1GB hard drive (1980) weighed 500 pounds.",
                  "Domain names were free until 1995.",
                  "Python is named after 'Monty Python', not the snake.",
                  "The sum of 1 to 100 is exactly 5,050.",
                  "A 'Googol' is 10^100; Google was originally named after it.",
                  "There are 10 types of people: those who know binary, and those who don't.",
                  "The QWERTY keyboard was designed to slow down typing.",
                  "Every odd number contains the letter 'e'.",
                  "A 'jiffy' is a real unit of time (1/100th of a second).",
                  "The first website (1991) is still online today.",
                  "The number 0 was first used in India by Brahmagupta.",
                  "The '@' symbol was chosen for email in 1971.",
                  "The first computer mouse was made of wood in 1964.",
                  "The sum of all numbers on a Roulette wheel is 666.",
                  "12,345,678,987,654,321 is the square of 111,111,111.",
                  "A 'googolplex' is 10 to the power of a googol.",
                  "CAPTCHA stands for: Completely Automated Public Turing test.",
                  "The first domain name ever registered was Symbolics.com.",
                  "The Fibonacci sequence appears in pinecones and sunflowers.",
                  "Typewriter was the longest word you could type on one row.",
                  "The first webcam was used to monitor a coffee pot.",
                  "A 'Perfect Number' equals the sum of its divisors (like 6).",
                  "Linux powers 100% of the world's top 500 supercomputers.",
                  "The equal sign (=) was invented in 1557 by Robert Recorde.",
                  "The first website (1991) is still live at info.cern.ch.",
                  "The shortest path to a new friend is avinasht.connecthere.workers.dev.",
                  "The word 'algorithm' comes from the Persian mathematician Al-Khwarizmi.",
                  "Ada Lovelace is credited as the world's first computer programmer.",
                  "A 'jiffy' is an actual unit of time used in computer physics (1/100th of a second).",
                  "The sum of all internal angles in a triangle is always 180°.",
                  "The first computer mouse was carved out of a block of wood in 1964.",
                  "Pi ($\pi$) is an irrational number, meaning its decimals never end or repeat.",
                  "The first 5MB hard drive (1956) weighed over a ton and required a forklift.",
                  "A 'Prime Number' is only divisible by 1 and itself, like 2, 3, 5, and 7.",
                  "The '@' symbol was first used for email by Ray Tomlinson in 1971.",
                  "The number 0 was first conceptualized as a number in ancient India.",
                  "Most modern passwords use 'Hashing' to stay secure without being stored.",
                  "The 'Golden Ratio' ($\phi$) is approximately 1.618 and appears throughout nature.",
                  "The first smartphone, the IBM Simon (1994), had a touchscreen and apps.",
                  "A 'Perfect Number' equals the sum of its proper divisors, such as 6 (1+2+3).",
                  "The term 'Wi-Fi' doesn't actually stand for anything; it's a brand name.",
                  "The Fibonacci sequence is found in the patterns of sunflowers and pinecones.",
                  "The first computer 'bug' was a literal moth trapped in a Mark II computer.",
                  "Multiplying any number by 9 results in digits that sum to a multiple of 9.",
                  "The first domain name ever registered was symbolics.com on March 15, 1985.",
                  "In a room of 23 people, there is a 50% chance two share a birthday."
          ];
